// <auto-generated />
using DucommForge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DucommForge.Data.Migrations
{
    [DbContext(typeof(DucommForgeDbContext))]
    [Migration("20260222014223_SyncModel_2026_02_21_02")]
    partial class SyncModel_2026_02_21_02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DucommForge.Data.AppSetting", b =>
                {
                    b.Property<int>("AppSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppSettingId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.Agency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DispatchCenterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Owned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Short")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgencyId");

                    b.HasIndex("DispatchCenterId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.DispatchCenter", b =>
                {
                    b.Property<int>("DispatchCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DispatchCenterId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DispatchCenters");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.Station", b =>
                {
                    b.Property<int>("StationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Esz")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StationKey");

                    b.HasIndex("AgencyId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.Unit", b =>
                {
                    b.Property<int>("UnitKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Jump")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("UnitKey");

                    b.HasIndex("StationKey");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.Agency", b =>
                {
                    b.HasOne("DucommForge.Data.Entities.DispatchCenter", "DispatchCenter")
                        .WithMany()
                        .HasForeignKey("DispatchCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispatchCenter");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.Station", b =>
                {
                    b.HasOne("DucommForge.Data.Entities.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("DucommForge.Data.Entities.Unit", b =>
                {
                    b.HasOne("DucommForge.Data.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });
#pragma warning restore 612, 618
        }
    }
}
