// <auto-generated />
using DucommForge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DucommForge.Migrations
{
    [DbContext(typeof(DucommForgeDbContext))]
    [Migration("20260221215505_InitSchema")]
    partial class InitSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DucommForge.Data.Agency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("DispatchCenterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Owned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Short")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AgencyId");

                    b.HasIndex("DispatchCenterId");

                    b.HasIndex("DispatchCenterId", "Short")
                        .IsUnique();

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("DucommForge.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("DucommForge.Data.DispatchCenter", b =>
                {
                    b.Property<int>("DispatchCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DispatchCenterId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DispatchCenters");
                });

            modelBuilder.Entity("DucommForge.Data.Station", b =>
                {
                    b.Property<int>("StationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Esz")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StationKey");

                    b.HasIndex("AgencyId");

                    b.HasIndex("AgencyId", "StationId")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("DucommForge.Data.Unit", b =>
                {
                    b.Property<int>("UnitKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("Jump")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("StationKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnitKey");

                    b.HasIndex("StationKey");

                    b.HasIndex("StationKey", "UnitId")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("DucommForge.Data.Agency", b =>
                {
                    b.HasOne("DucommForge.Data.DispatchCenter", "DispatchCenter")
                        .WithMany()
                        .HasForeignKey("DispatchCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispatchCenter");
                });

            modelBuilder.Entity("DucommForge.Data.Station", b =>
                {
                    b.HasOne("DucommForge.Data.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("DucommForge.Data.Unit", b =>
                {
                    b.HasOne("DucommForge.Data.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });
#pragma warning restore 612, 618
        }
    }
}
